### ISSUE TITLE
crashes on macOS

### ISSUE THREAD

**Issue by sma** [chrisnorman7/dart_sdl#2]
I tried to run version 0.8.4 on macOS 11.6.2 but it crashes **HARD**.  

And I'm afraid it cannot work.

A simple `Sdl()..init()` doesn't work because the library name is wrong, I think.

* When using Homebrew, the `libName` should be `libSDL2.dylib`.
* When using the library from [here](https://www.libsdl.org/download-2.0.php), the `libName` should be `SDL2.framework/SDL2`.

After this has been fixed, a single `sdl.createWindow` leads to this crash:

```
Assertion failed: (NSViewIsCurrentlyBuildingLayerTreeForDisplay() != currentlyBuildingLayerTree), function NSViewSetCurrentlyBuildingLayerTreeForDisplay, file /System/Volumes/Data/SWE/macOS/BuildRoots/9dc5c14c79/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-2022.60.130/AppKit.subproj/NSView.m, line 13412.

===== CRASH =====
si_signo=Illegal instruction: 4(4), si_code=1, si_addr=0x7fff206004be
version=2.16.0-134.0.dev (dev) (Thu Dec 23 21:23:33 2021 -0800) on "macos_x64"
pid=78117, thread=6151, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
isolate_instructions=0, vm_instructions=10deb4880
  pc 0x00007fff206004be fp 0x000070000b9539a0 __abort+0xa9
  pc 0x00007fff20600415 fp 0x000070000b9539e0 __abort+0x0
  pc 0x00007fff205ff7d8 fp 0x000070000b953a20 err+0x0
  pc 0x00007fff23082237 fp 0x000070000b953a50 NSViewSetCurrentlyBuildingLayerTreeForDisplay+0xd2
  pc 0x00007fff238578b8 fp 0x000070000b953ac0 NSWindowUpdateLayerTree+0x47
  pc 0x00007fff2308073f fp 0x000070000b953af0 -[NSWindow displayIfNeeded]+0xd7
  pc 0x00007fff230805a3 fp 0x000070000b953b50 __NSWindowGetDisplayCycleObserverForDisplay_block_invoke+0x289
  pc 0x00007fff2307eaa5 fp 0x000070000b953ba0 NSDisplayCycleObserverInvoke+0x9b
  pc 0x00007fff2307e630 fp 0x000070000b953d60 NSDisplayCycleFlush+0x3b9
  pc 0x00007fff26f15c86 fp 0x000070000b953da0 CA::Transaction::run_commit_handlers(CATransactionPhase)+0x5c
  pc 0x00007fff26f14a1d fp 0x000070000b953e80 CA::Transaction::commit()+0x177
  pc 0x00007fff26f31246 fp 0x000070000b953f40 CA::Transaction::release_thread(void*)+0xc6
  pc 0x00007fff206a998d fp 0x000070000b953f80 _pthread_tsd_cleanup+0x1e7
  pc 0x00007fff206abf65 fp 0x000070000b953fb0 _pthread_exit+0x46
  pc 0x00007fff206ab907 fp 0x000070000b953fd0 _pthread_start+0xeb
  pc 0x00007fff206a7443 fp 0x000070000b953ff0 thread_start+0xf
-- End of DumpStackTrace
```

According to other SDL issues elsewhere, this is caused by not pumping events. 

So let's do that:

```dart
void main() async {
  final sdl = Sdl(libName: 'libSDL2.dylib')..init();
  final window = sdl.createWindow('Hello, Stefan!')..show();
  await for (final event in sdl.events) {
    if (event is QuitEvent) break;
    print(event);
  }
  window.destroy();
  sdl.quit();
}
```

However, any other function call to macOS AppKit methods emits this error:

```
2021-12-29 17:48:06.508 dart[78236:5629928] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'
```

which is caused by Dart FFI not using the main thread when calling into foreign functions (see [here](https://github.com/dart-lang/sdk/issues/42570) for details).

**Comment by chrisnorman7** [comment]
Hi @sma,
Thank you so much for such a detailed issue.

If you update dart_sdl, you should get a newer version that autodetects the libraries you mention. I'm sure you already know this, but for anyone else stumbling across this in the future, the library files do need to be in the current working directory, or else you need to specify a custom library path.

As for the threading stuff, I'm not even sure that's something I can fix. I've been looking at the [issue](https://github.com/dart-lang/sdk/issues/38315) which your issue referenced, and it seems as though something called [libdispatch](https://apple.github.io/swift-corelibs-libdispatch/) needs to be used. If you can figure out how this should work (I don't have a mac), and make it happen, I'm more than happy to accept a PR.

Thanks again for being so detailed, it was really helpful.

**Comment by chrisnorman7** [comment]
Closing this for now as it's not seen any activity in a while, so I assume it's no longer a problem.

If it still is, please le me know.

**Comment by sada-narayanappa** [comment]
still a problem

**Comment by chrisnorman7** [comment]
Hi @sada-narayanappa,
Is everything still the same? Or do you just mean the threading stuff?
