### ISSUE TITLE
Error when using SDL2.dll (version 2.0.20)

### ISSUE THREAD

**Issue by Keithcat1** [chrisnorman7/dart_sdl#3]
Dart: 2.16.1
Windows 10 (64-bit)

When using SDL2.dll gotten from [libsdl.org](https://libsdl.org) I got the following error:
SdlError (17): Unrecognised `SDL_WindowEventID` member.
#0      IntToC.toWindowEventID (package:dart_sdl/src/enumerations.dart:3243:9)
#1      Sdl.pollEvent (package:dart_sdl/src/sdl.dart:702:37)
#2      Game._getNewWindowEvents (package:audiogame/src/game.dart:50:53)
#3      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:180:26)
#4      Game._eventLoop (package:audiogame/src/game.dart:102:23)
<asynchronous suspension>
#5      Game.run (package:audiogame/src/game.dart:126:3)
<asynchronous suspension>
#6      main (file:///C:/py/dart/audiogame/example/simple.dart:46:2)
<asynchronous suspension>

Thanks for writing nice SDL bindings. Dunno if I could've been bothered to do it myself.

**Comment by chrisnorman7** [comment]
Hi @Keithcat1,
I'm downloading the new release now.

As an aside, put your shell output inside a code block, so it doesn't match the stack depths to issues. :)

**Comment by chrisnorman7** [comment]
Closed this in 36279a9182ce8ef5efc4e9e919d803dceb42575f, and forgot to do it with the commit message.
